ifneq (,$(filter ndef,$(USEMODULE)))
  DIRS += ndef
endif
ifneq (,$(filter nfct,$(USEMODULE)))
  DIRS += nfct
endif
ifneq (,$(filter nfc_t2t,$(USEMODULE)))
  DIRS += t2t
endif

include $(RIOTBASE)/Makefile.base
